/********************
    性能仓库表结构、索引初始化
  Derby v1.0版本
********************/
-- 建表
CREATE TABLE "PERF"."PERF_WEBSPHERE"(
   "ID" BIGINT NOT NULL,
   "CREATE_TIME" TIMESTAMP NOT NULL,
   "PERF_DATA" CLOB NOT NULL,
   CONSTRAINT "PK_PERF_WEBSPHERE" PRIMARY KEY ("ID")
);
-- 建主键、索引和约束
CREATE UNIQUE INDEX PK_PERF_WEBSPHERE ON PERF.PERF_WEBSPHERE("ID");
CREATE INDEX IDX_PERF_WEBSPHERE_TIME ON PERF.PERF_WEBSPHERE("CREATE_TIME" DESC);
-- 单独配置主键和约束(第2种方法，用于表结构已建立添加主键约束)
ALTER TABLE PERF.PERF_WEBSPHERE ADD CONSTRAINT PK_PERF_WEBSPHERE PRIMARY KEY (ID);
-- 删除主键、索引和约束
ALTER TABLE PERF.PERF_WEBSPHERE DROP CONSTRAINT PK_PERF_WEBSPHERE;
DROP INDEX PERF.IDX_PERF_WEBSPHERE_TIME;
ALTER TABLE PERF.PERF_WEBSPHERE DROP CONSTRAINT IDX_PERF_WEBSPHERE_TIME;
-- 序列管理
CREATE SEQUENCE PERF.SEQ_PERF_WEBSPHERE AS BIGINT START WITH 10000000 INCREMENT BY 1 MAXVALUE 19999999 CYCLE;
-- 序列当前值（不太正确）
SELECT CURRENTVALUE FROM SYS.SYSSEQUENCES WHERE SEQUENCENAME='SEQ_PERF_WEBSPHERE';
-- 序列的NEXT值
VALUES NEXT VALUE FOR PERF.SEQ_PERF_WEBSPHERE;
-- 删除序列
DROP SEQUENCE PERF.SEQ_PERF_WEBSPHERE RESTRICT;
-- 删除schema
DROP SCHEMA PERF RESTRICT;
-- 删除表结构
DROP TABLE PERF.PERF_WEBSPHERE;
-- 当前时间戳
VALUES CURRENT_TIMESTAMP;
SELECT CURRENT_TIMESTAMP FROM SYSIBM.SYSDUMMY1;
-- 查询所有聚合体
SELECT *
  FROM sys.sysconglomerates t1, sys.sysschemas t2
 WHERE t1.schemaid = t2.schemaid
   AND t2.schemaname = 'PERF';
SELECT *
  FROM sys.sysconglomerates t1, sys.systables t2
 WHERE t1.tableid = t2.tableid AND t2.tablename = 'PERF_WEBSPHERE'
   AND t1.conglomeratename = 'IDX_PERF_WEBSPHERE_TIME';
-- 查询所有约束
SELECT *
  FROM sys.sysconstraints t1, sys.systables t2
 WHERE t1.tableid = t2.tableid
   AND t1.constraintname = 'PK_PERF_WEBSPHERE'
   AND t1.type = 'P';
-- 查询符合条件的表结构
SELECT 1
  FROM sys.systables t1, sys.sysschemas t2
 WHERE t1.tablename = 'PERF_WEBSPHERE'
   AND t1.schemaid = t2.schemaid
   AND t2.schemaname = 'PERF';
